#!/usr/bin/Rscript

## -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
library(getopt)
library(reshape2)
library(dplyr)
library(tidyr)

## --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


command = matrix(c(
    'mods1_count', 'm1', 1, "character",
    'mods2_count', 'm2', 1, "character",
    'synteny_table', 't', 1, "character",
    'synteny_count', 'c', 1, "character"), byrow=TRUE, ncol=4)

args = getopt(command)


##help info------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

if (!is.null(args$help) || is.null(args$mods1_count) || is.null(args$mods2_count) || is.null(args$synteny_table) || is.null(args$synteny_count)) {
  cat(paste(getopt(command, usage = T), "\n"))
  q()
}

## ------------------------------------------------------------Load modification meta_table------------------------------------------------------------------------------------

#Load modification meta table for speceis 1 
MODs_meta_1 <- read.csv(args$mods1_count, header = T)

#Load modification meta table for speceis 2
MODs_meta_2 <- read.csv(args$mods2_count, header = T)

#Combined annotations from different two species 
MODs_meta <- rbind(MODs_meta_1,MODs_meta_2)

#combine mods from different genomic element but under the same gene
MODs_meta <- MODs_meta %>% group_by(Gene.ID)%>% dplyr::mutate(sum(Counts))
MODs_meta <- unique(data.frame(Gene.ID = MODs_meta[,2], MODs_counts = MODs_meta[,4]))


## -------------------------------------------------------------Load syntenic gene list generated by CoGe------------------------------------------------------------------------
#Load syntenic genes list
synteny <- read.csv(args$synteny_table, header = F, na.strings=c("","NA"))

## -------------------------------------------------------- Combine and parse the dataframe ----------------------------------------------------------------------------------------

for (i in 1:ncol(synteny)){
  synteny.df <- left_join(data.frame(Gene.ID = synteny[,i]),MODs_meta, by = "Gene.ID")
  assign(paste0("sub_synteny_",i),synteny.df)
}

#merge all sub_synteny file derived from each column 
merge_list <- lapply(ls(pattern = "sub_synteny_"), get)
synteny_combine <- bind_cols(merge_list)

#Replace all na counts as zero
synteny_combine[is.na(synteny_combine)] = 0

#Remove rows without any modifications
#calculate the maximum colnumbers need to be sum up
select_col <- seq(2,ncol(synteny_combine),2)

synteny_combine$Total <- rowSums(synteny_combine[,c(select_col)])
synteny_clean <- synteny_combine[synteny_combine$Total != 0,]


## --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
write.csv(synteny_clean,args$synteny_count, row.names = F)
 
